parameters:

  header:
    ## Header information is used for logging. It is good practice to give your simulations explicit names
    title: Isotropic Elastic simulation # name for your simulation
    # A detailed description for your simulation
    description: |
      Material systems : Elastic domain (1)
      Interfaces : None
      Sources : Force source (1)
      Boundary conditions : Neumann BCs on all edges

  simulation-setup:
    ## quadrature setup
    quadrature:
      quadrature-type: GLL4

    ## Solver setup
    solver:
      time-marching:
        time-scheme:
          type: Newmark
          dt: 0.16
          nstep: 250

    simulation-mode:
      forward:
        writer:
          seismogram:
            format: "ascii"
            directory: "OUTPUT_FILES/results"

          # display:
          #   format: VTKHDF
          #   directory: /Users/lsawade/SPECFEMPP/benchmarks/build/release/dim3/homogeneous_halfspace/OUTPUT_FILES/vtk/
          #   field: displacement
          #   simulation-field: forward
          #   time-interval: 5

  receivers:
    stations: "DATA/STATIONS"
    angle: 0.0
    seismogram-type:
      - displacement
    nstep_between_samples: 1

  ## Runtime setup
  run-setup:
    number-of-processors: 1
    number-of-runs: 1

  ## databases
  databases:
    mesh-database: "OUTPUT_FILES/DATABASES/proc000000_Database.bin"

  ## sources
  sources: "force.yaml"
