parameters:

  header:
    ## Header information is used for logging. It is good practice to give your simulations explicit names
    title: fluid-solid-nonconforming  # name for your simulation
    # A detailed description for your simulation
    description: |
      Material systems : Elastic domain (1), Acoustic domain (1)
      Interfaces : Acoustic-elastic interface (1) (orientation horizontal with acoustic domain on top)
      Sources : Moment-tensor (234)
      Boundary conditions : Absorbing left, right, and bottom; free surface top

  simulation-setup:
    ## quadrature setup
    quadrature:
      quadrature-type: GLL4

    ## Solver setup
    solver:
      time-marching:
        type-of-simulation: forward
        time-scheme:
          type: Newmark
          dt: 1.000e-3
          nstep: 16250

    simulation-mode:
      forward:
        writer:
          seismogram:
            format: ascii
            directory: OUTPUT_FILES/seismograms

          display:
            format: PNG
            directory: OUTPUT_FILES/display
            field: pressure
            simulation-field: forward
            time-interval: 250

  receivers:
    stations: OUTPUT_FILES/STATIONS
    angle: 0.0
    seismogram-type:
      - pressure
    nstep_between_samples: 1

  ## Runtime setup
  run-setup:
    number-of-processors: 1
    number-of-runs: 1

  ## databases
  databases:
    mesh-database: OUTPUT_FILES/database.bin

  ## sources
  sources: line_source.yaml
